// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhLic15w4TFfvn33raWOLRDQQTLxYBSRo',
    appId: '1:87957247657:web:bd4fd7eb97406df87cfbb8',
    messagingSenderId: '87957247657',
    projectId: 'diaryapp-ykuo',
    authDomain: 'diaryapp-ykuo.firebaseapp.com',
    storageBucket: 'diaryapp-ykuo.firebasestorage.app',
    measurementId: 'G-CTKGGSXDK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvBT7egMWsedyD78v40RFIUsQeRoV1BwQ',
    appId: '1:87957247657:android:510c27ada53609677cfbb8',
    messagingSenderId: '87957247657',
    projectId: 'diaryapp-ykuo',
    storageBucket: 'diaryapp-ykuo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDikr9_yq-UBwlPDhAFjsQDMZFBDI_J5e0',
    appId: '1:87957247657:ios:8d8399e287139b7c7cfbb8',
    messagingSenderId: '87957247657',
    projectId: 'diaryapp-ykuo',
    storageBucket: 'diaryapp-ykuo.firebasestorage.app',
    androidClientId: '87957247657-t8gvqr8chj1o9ofeetrs67hqsrqk0tda.apps.googleusercontent.com',
    iosClientId: '87957247657-c9qqhpustnogl4g2gs9a2nsgtk4r2mii.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDikr9_yq-UBwlPDhAFjsQDMZFBDI_J5e0',
    appId: '1:87957247657:ios:8d8399e287139b7c7cfbb8',
    messagingSenderId: '87957247657',
    projectId: 'diaryapp-ykuo',
    storageBucket: 'diaryapp-ykuo.firebasestorage.app',
    androidClientId: '87957247657-t8gvqr8chj1o9ofeetrs67hqsrqk0tda.apps.googleusercontent.com',
    iosClientId: '87957247657-c9qqhpustnogl4g2gs9a2nsgtk4r2mii.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhLic15w4TFfvn33raWOLRDQQTLxYBSRo',
    appId: '1:87957247657:web:086e93775e0d699f7cfbb8',
    messagingSenderId: '87957247657',
    projectId: 'diaryapp-ykuo',
    authDomain: 'diaryapp-ykuo.firebaseapp.com',
    storageBucket: 'diaryapp-ykuo.firebasestorage.app',
    measurementId: 'G-FE44PFSFPF',
  );
}
